name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8  
      - name: Build, Test and Publish package (.jar file) to GitHub
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
      - uses: akhileshns/heroku-deploy@v3.0.4
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "petclinic-traditional-ci-cd"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
